version: '3'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    restart: unless-stopped
    container_name: embedding-backend
    environment:
      - PYTHONUNBUFFERED=1

